### ISSUE TITLE
c++ syntax in the file mm_fill_util.c

### ISSUE THREAD

**Issue by AndrewUshakov** [goma/goma#258]
I just tried to build the latest GOMA version in CENTOS 7 (gcc 4.8.5) using easy-goma-builder and got compiling errors in function ‘get_supg_tau (mm_fill_util.c), where c++ syntax is used in several loops after commit from May 16 2019...

I am not sure, which variant is better: correct build script or the c-file?

`
/home/andrew/goma/src/mm_fill_util.c: In function ‘get_supg_tau’:
/home/andrew/goma/src/mm_fill_util.c:5329:3: error: ‘for’ loop initial declarations are only allowed in C99 mode

   for (int i = 0; i < VIM; i++) {
`

**Comment by wortiz** [comment]
Are you using cmake to build?

We've switched to using c99 for our standard

https://github.com/goma/goma/blob/master/src/Makefile#L254

gcc 4.8.5 is still a little old so it doesn't default to c99 yet so you have to add flags

If using cmake you can add it with ${PROJECT_NAME}_USER_C_FLAGS 

I'll have to adjust cmake to make it default

**Comment by AndrewUshakov** [comment]
I used easy-goma-builder.sh. It found appropriate version of cmake in my distributive, so probably answer is yes.

P.S. CENTOS 7 is installed at our corporate standard...

**Comment by wortiz** [comment]
I've added a pull request to fix this it should be merged shortly

gcc 4.8.5 came out in 2015 so it is a little old now, Centos/Redhat have the devtoolset packages to get access to newer gcc/development packages

You are seeing this issue because before 5.1 gcc defaulted to gnu90 standard, now it defaults to gnu11 so we didn't pick up this error in testing.
