### ISSUE TITLE
History Fix

### ISSUE THREAD

**Issue by acochrane** [goma/goma#67]
I was able to fix all the rebase issues dshari had been having.
I have pushed them to my master branch.

Does anyone care to inspect and push them to the goma/goma master branch?
There's now an empty commit due to the conflict resolution, it can probably be deleted it in a further rebase.

**Comment by wortiz** [comment]
I haven't done a ton of inspecting but I think Daniel's clean_master branch preserved history a bit better. 

Yours seems to be missing quite a bit more commits and reordered quite a few as well. I'm not sure if you had a reason for this.

I'll let someone else chime in but it looks like force pushing to fix the history may be the best option (I haven't been able to find anything better).

**Comment by prschun** [comment]
Unless Scott has time to weigh in I'm going to have to trust you guys on this.   I really appreciate your efforts here Andrew, Daniel and Weston.  Let's however make sure the root cause of this is understood and put measures in place to keep guys like me from screwing up.   Randy.

Ps you might want to get Robert's concurrence here before any major commits

Sent from my iPhone

On Jan 30, 2015, at 6:22 PM, "Weston Ortiz" <notifications@github.com<mailto:notifications@github.com>> wrote:


I haven't done a ton of inspecting but I think Daniel's clean_master branch preserved history a bit better.

Yours seems to be missing quite a bit more commits and reordered quite a few as well. I'm not sure if you had a reason for this.

I'll let someone else chime in but it looks like force pushing to fix the history may be the best option (I haven't been able to find anything better).

-

**Comment by saroberts** [comment]
I’d like to take a look at the changes to confirm, if I can.  Who’s is the best?  Daniels?

I’ll try to put more measures in place, i.e. to not allow non linear commits.

**Comment by saroberts** [comment]
Okay, so I just took a few minutes to investigate.  I think I see part of the issue.  Somehow people are making changes locally, then merging the changes from github in and then pushing.  When you do that, you get commits that look like this:
                Merge branch 'master' of https://github.com/goma/goma
You should not see that in your history.

Additionally, I think that there are been some pushes with local changes that don’t belong in the github version.  For example, in the last 20 or so commits, there are a lot of changes to the Makefile that I don’t think should be there.  One needs to be careful with what files are “added” to a commit.  And remember, prefer a rebase (which happens when you do a git pull) than a merge.

Here’s what I think really should be done to fix these errors.

1)      I think the last really clean commit is bb94d70943ae7ed21d8672092e7ceab4cee54863

2)      Somebody reset their master to that commit (bb94d70943ae7ed21d8672092e7ceab4cee54863)

3)      Use gitk to go through the commits after that and simply cherry-pick the “good” commits, those that don’t contain bad merges, unnecessary changes, etc.

4)      Once this is done and there’s a clean master branch, force push that over to github.
Unfortunately, I don’t really have time to do this myself  Maybe this is what Daniel has done; I haven’t had the chance to see his.

Here are a few resources for git; the cheat sheat is really nice:
https://training.github.com/kit/downloads/github-git-cheat-sheet.pdf
https://help.github.com/articles/good-resources-for-learning-git-and-github/

The general development workflow should be:

1)      Write your code

2)      Commit the files you want to share locally (git commit)

3)      Pull anything new from the repository and resolve conflicts (git pull)

4)      Push (git push), but prefer a “pull request”, that forces GitHub to check for conflicts and bad history.

--Scott

**Comment by dshari** [comment]
Hi all,

Andrew and I followed Scott's instructions to get a new Goma history.  We did a force push and the new goma/master reflects these changes.  We can now rebase cleanly with this branch.

From here on out we are going to have a new github policy.  Write privileges will be restricted to a chosen few, the AML group and Scott.  Changes to the master branch will all be done through pull requests, and this should prevent the issue of "bad histories" showing up again.  Those of us at the AML will review the pull requests and suggest/help with changes to the pull requests.

The whole point of git is to have everything decentralized.  Thus, you do not need to push changes to the master branch in order for your changes to be seen.  Read Scott's post above.

If there are changes you would like to work that aren't in the master, there are ways to work with other developer's forks and branches.  

Let us know if you have any questions.
